name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - stable
      prerelease:
        description: 'Pre-release type (optional)'
        required: false
        type: choice
        options:
          - none
          - alpha
          - beta
          - rc

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        id: bump
        run: |
          # Bump main version
          if [ "${{ github.event.inputs.prerelease }}" != "none" ] && [ -n "${{ github.event.inputs.prerelease }}" ]; then
            uv version --bump ${{ github.event.inputs.bump }} --bump ${{ github.event.inputs.prerelease }}
          else
            uv version --bump ${{ github.event.inputs.bump }}
          fi

          # Get new version
          NEW_VERSION=$(uv version --short)
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Update lockfile
        run: uv lock

      - name: Commit version bump
        run: |
          git add pyproject.toml uv.lock
          git commit -m "chore: bump version to ${{ steps.bump.outputs.version }}"
          git push

      - name: Create git tag
        run: |
          git tag -a "v${{ steps.bump.outputs.version }}" -m "Release v${{ steps.bump.outputs.version }}"
          git push origin "v${{ steps.bump.outputs.version }}"

      - name: Build package
        run: uv build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump.outputs.version }}
          name: Release v${{ steps.bump.outputs.version }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease != 'none' && github.event.inputs.prerelease != '' }}
          files: dist/*
          generate_release_notes: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
